# Implimentaion of manual backprop in neural nets

## 1. Derivatives

### 1.1  Scalar case

Given a function f : R → R, the derivative of f at a point x ∈ R is defined as: \
![scalar derivativ formula](resources/scalar-derivative-formula.png)

In [1]:
f = lambda x: 3*x
f(4)

12

In [2]:
# derivative of the function 'f' by the given formula
# taking h = 0.001

(f(4+0.001) - f(4))/0.001

3.0000000000001137

### jacobian

In [3]:
import numpy as np

In [4]:
X = np.random.rand(5)
X

array([0.94174308, 0.2207552 , 0.13450892, 0.63251016, 0.56993103])

In [5]:
f = lambda x: x*x
f(X)

array([0.88688003, 0.04873286, 0.01809265, 0.4000691 , 0.32482138])

In [6]:
w1 = np.random.rand(5,5)
b1 = np.random.rand(5)

w2 = np.random.rand(5,1)
b2 = np.random.rand(1)
w1,b1, w2,b2

(array([[0.53559417, 0.22255088, 0.63812681, 0.47331755, 0.80679868],
        [0.17133279, 0.05374136, 0.06006048, 0.88769736, 0.71830963],
        [0.25546734, 0.93652523, 0.43554243, 0.26423482, 0.90483233],
        [0.54243403, 0.99104962, 0.13193984, 0.38314896, 0.76625985],
        [0.51312402, 0.12296206, 0.3093766 , 0.45405196, 0.15908344]]),
 array([0.1714142 , 0.35060353, 0.80398397, 0.15259947, 0.7515517 ]),
 array([[0.4244946 ],
        [0.13466515],
        [0.0412037 ],
        [0.92715733],
        [0.65588491]]),
 array([0.47273462]))

In [21]:
x = np.random.rand(10,5)
y = x @ [[0.8], [0.3], [0.75], [0.5], [0.2]] + 0.43
y.shape

(10, 1)

In [22]:
z1 = x @ w1 + b1
z1.shape

(10, 5)

In [23]:
z2 = z1 @ w2 + b2
z2.shape

(10, 1)

In [24]:
loss = np.sum((y-z2)**2) / (len(z2) *2)

In [25]:
loss

2.7322169922473796

In [26]:
dldz2 = (z2 - y)*(2/len(z2)) 
dldz2

array([[0.58443753],
       [0.62800397],
       [0.30943124],
       [0.44039946],
       [0.50182909],
       [0.36612148],
       [0.38083333],
       [0.43264027],
       [0.57537338],
       [0.3331283 ]])

In [27]:
dlw2 = z1.transpose() @ dldz2
dlw2

array([[ 5.43607979],
       [ 7.0438933 ],
       [ 7.17990786],
       [ 6.18345152],
       [11.16008735]])

In [29]:
dldb2 = dldz2
dldz1 = dldz2 @ w2.transpose()

In [30]:
dldz1.shape

(10, 5)

In [31]:
dldw1 = x.transpose() @ dldz1
dldw1.shape

(5, 5)

In [32]:
dldb1 = dldz1
dldx = dldz1 @ w1.transpose()