# Implimentaion of manual backprop in neural nets

## 1. Derivatives

### 1.1  Scalar case

Given a function f : R → R, the derivative of f at a point x ∈ R is defined as: \
![scalar derivativ formula](resources/scalar-derivative-formula.png)

In [1]:
f = lambda x: 3*x
f(4)

12

In [2]:
# derivative of the function 'f' by the given formula
# taking h = 0.001

(f(4+0.001) - f(4))/0.001

3.0000000000001137

### jacobian

In [3]:
import numpy as np

In [4]:
X = np.random.rand(5)
X

array([0.94720717, 0.43867335, 0.52658615, 0.20750268, 0.9247352 ])

In [5]:
f = lambda x: x*x
f(X)

array([0.89720142, 0.1924343 , 0.27729298, 0.04305736, 0.85513518])

In [9]:
w1 = np.random.rand(5,5)
b1 = np.random.rand(5)

w2 = np.random.rand(5,1)
b2 = np.random.rand(1)
w1,b1, w2,b2

(array([[0.22938472, 0.17398476, 0.5672685 , 0.87379602, 0.51999036],
        [0.10389021, 0.4333656 , 0.32006618, 0.26473278, 0.39615752],
        [0.46735949, 0.97925006, 0.69537756, 0.04853546, 0.36401545],
        [0.29489074, 0.39532867, 0.21930055, 0.95863886, 0.60014275],
        [0.57245565, 0.62639105, 0.4660835 , 0.40248493, 0.81181349]]),
 array([0.37329218, 0.59757464, 0.0734772 , 0.06035677, 0.46293073]),
 array([[0.00559239],
        [0.62531529],
        [0.33991946],
        [0.25545277],
        [0.20465057]]),
 array([0.66548976]))

In [11]:
x = np.random.rand(10,5)
y = x*0.8 + 0.43
y

array([[0.67098225, 0.96944772, 1.22125096, 0.98424427, 0.85933315],
       [1.03401715, 0.52162864, 1.19903526, 0.56987209, 0.94908527],
       [0.62413116, 0.98751987, 0.73727548, 1.0876131 , 0.83787004],
       [1.16060623, 1.05880854, 0.68751156, 0.91006922, 0.67837513],
       [0.93175443, 0.53926236, 0.44748156, 0.54880258, 1.07597917],
       [0.48792756, 0.96292598, 0.68523015, 1.14515271, 0.93009154],
       [0.87291199, 0.76681349, 0.63014806, 1.0644416 , 0.68613335],
       [0.51482813, 0.93576781, 0.56694985, 0.59277692, 0.77945913],
       [0.89853823, 0.65737894, 1.16744345, 1.15782158, 1.00230211],
       [0.82039989, 0.7795845 , 0.55292775, 1.04849701, 0.44651805]])

In [20]:
z1 = x @ w1 + b1
z1.shape

(10, 5)

In [27]:
z2 = z1 @ w2 + b2
z2.shape

(10, 1)

In [37]:
loss = np.sum((y-z2)**2) / (len(z2) *2)

In [38]:
loss

11.934135113098563

In [39]:
dldz2 = 2*x *(z2 - y) 
dldz2

array([[1.74756975, 3.50948353, 4.64954031, 3.58524317, 2.91130107],
       [3.37769341, 0.62976549, 3.98322086, 0.94447389, 3.01296743],
       [1.17553528, 2.86949601, 1.77374944, 3.22010874, 2.25185828],
       [3.61890294, 3.27469782, 1.58009725, 2.67860881, 1.52970902],
       [1.88247027, 0.51713944, 0.08675149, 0.55945983, 2.19065376],
       [0.36463276, 2.72172597, 1.48068619, 3.32658298, 2.59508652],
       [2.12873633, 1.70814117, 1.08342916, 2.74548557, 1.35063607],
       [0.36550972, 1.64702148, 0.57224803, 0.66965688, 1.27456451],
       [3.37408864, 1.77451241, 4.81480227, 4.76948815, 3.97286366],
       [1.55311379, 1.42641047, 0.57123842, 2.10785087, 0.08115264]])

In [54]:
dlw2 = z1.transpose() @ dldz2
dlw2

array([[24.97903014, 24.69112283, 28.58545713, 31.55828789, 27.79938562],
       [38.68571345, 39.4483052 , 45.41573158, 49.97649266, 43.41173061],
       [25.44932341, 24.28225941, 29.08645009, 31.04622296, 27.38029787],
       [29.36124507, 29.33098715, 30.94060007, 37.59091894, 30.48776112],
       [37.44957634, 37.903672  , 41.49161631, 47.89689216, 41.04785609]])

In [55]:
dldb2 = dldz2
dldz1 = dldz2 @ w2

In [60]:
dldz1.shape

(10, 1)

In [57]:
dldw1 = x.transpose() @ dldz1
dldw1.shape

(5, 1)

In [58]:
dldb1 = dldz1
dldx = dldz1 @ w1.transpose()

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 1)